### ISSUE TITLE
No strikethrough text in description- and history-view

### ISSUE THREAD

**Issue by zedar187** [redminenb/redminenb#32] opened 2015-03-24 15:04 UTC
As stated in the title, the text on the tasks-panel won't strike through.
See attached image.

![redminenb](https://cloud.githubusercontent.com/assets/5468685/6804572/b2107418-d23e-11e4-8ad6-15f5de65cbc1.jpg)

Is this plugin-related, or a problem of the netbeans-ui?

**Comment by matthiasblaesing** [comment] 2015-03-24 21:15
The problem is verified - and will be fixed in next version of redminenb. I pushed the fix as:

https://github.com/redminenb/redminenb/commit/aed3f6fd9c4f608a1c4aa5cc65bf04cf30350737

The problem is rooted in the limited rendering abilities of the java component used to render the markup. The fix replaces the generated <del>-Tag by a <span>-Tag with text-decoriation: line-through css style.

Thank you for your report!

**Closed by matthiasblaesing** 2015-03-24 21:15 UTC
