### ISSUE TITLE
Search tasks opened with error

### ISSUE THREAD

**Issue by exru** [redminenb/redminenb#31] opened 2015-03-19 07:02 UTC
I am very glad what you had removed SSL bug.
But the next error have been occurring if i'm trying to open Tasks within my broken SSL certificate:
java.lang.NullPointerException
	at com.kenai.redminenb.query.RedmineQueryController$9.run(RedmineQueryController.java:514)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)

**Comment by matthiasblaesing** [comment] 2015-03-19 21:16
Could you please attach the message.log (http://wiki.netbeans.org/FaqLogMessagesFile) here or supply it somewhere where I can take a look at it? This looks as if the client was not able to get the list of trackers from the redmine system. The big question: why??

**Comment by exru** [comment] 2015-03-23 03:06
I'm sorry this is complete information.





**Comment by matthiasblaesing** [comment] 2015-03-24 20:49
Sorry - I need more information - I can only speculate - if your instance is available over the internet it would help if you could give me a temporary account to check it myself.

**Comment by exru** [comment] 2015-03-25 05:29
Dear friend i want to help you. But i am not a java programmer. I'll give you our corporative url https://rm.freematiq.com:1443 and i can't give you my login\password because my boss will killing me for secureless.

**Comment by matthiasblaesing** [comment] 2015-03-25 18:30
Thank you for your trust. The bad news: It works for me. I can't provie it as I don't want to attach an image potentially leaking your informations. My setup:

netbeans 8.0.2
redminenb 1.7 (I always install latest stable version before I upload it)
SSL Certificate Exception 0.9

I added your installation to my repositories - when trying to connect while setting the account up I have to accept the ssl certificate. After that I issue "Find tasks" and I'm presented with the normal search dialog and trackers are correctly listed. When doing this I have to accept the certificate multiple times. After accepting it "forever" I get a normal workflow.

A complete protocol - what I did:
1. Create Task Repository
2. Enter credentials you provided
3. Click "Connect"
4. Popup: "Invalid Certificate" => Accept once
5. Popup "Certificate does not match hostname" => Accept once
6. Output: "Successfully authenticated"
7. Accept by clicking ok
8. Right click on new repository and select "Find Tasks"
9. Popup: "Invalid Certificate" => Accept once
10. Popup "Certificate does not match hostname" => Accept once
11. Window is opened and Project, Tracker, Status, Priority, Assigne and Watchers are all filled

I was able to reproduce your problem when I modified my test above and choose "Decline" in step 9. In this case the connection can't be established and the tracker list can't be loaded. I also found evidence for this in the IDE Log (you can open it via View -> IDE Log). This showed me:

```
WARNING [com.kenai.redminenb.Redmine]: Failed to retrieve project list
javax.net.ssl.SSLException: Hostname did not verify
	at com.kenai.redminenb.repository.RedmineManagerFactoryHelper$1.verify(RedmineManagerFactoryHelper.java:42)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:641)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:44)
Caused: com.taskadapter.redmineapi.RedmineTransportException: Cannot fetch data from https://rm.freematiq.com:1443/projects.json 
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:55)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineAuthenticator.sendRequest(RedmineAuthenticator.java:52)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.BasicSimplifier.sendRequest(BasicSimplifier.java:24)
	at com.taskadapter.redmineapi.internal.Transport.send(Transport.java:555)
	at com.taskadapter.redmineapi.internal.Transport.getObjectsList(Transport.java:428)
	at com.taskadapter.redmineapi.internal.Transport.getObjectsList(Transport.java:396)
	at com.taskadapter.redmineapi.ProjectManager.getProjects(ProjectManager.java:66)
[catch] at com.kenai.redminenb.repository.RedmineRepository.getProjects(RedmineRepository.java:227)
	at com.kenai.redminenb.query.RedmineQueryController$9.run(RedmineQueryController.java:528)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
SEVERE [org.openide.util.RequestProcessor]: Error in RequestProcessor com.kenai.redminenb.query.RedmineQueryController$9
java.lang.NullPointerException
	at com.kenai.redminenb.query.RedmineQueryController$9.run(RedmineQueryController.java:528)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

While your problem indicates a problem getting the tracker list, both should show up this way (if your on redminenb 1.7).

I was able to get less questions when I just choose "Accept forever" for both invalid certificate and invalid hostname popups.

I hope this helps a bit.

**Comment by matthiasblaesing** [comment] 2015-04-02 17:57
Closing as a connection can be made with a current version of the plugin. Feel free to reopen if you experience more problems.

**Closed by matthiasblaesing** 2015-04-02 17:57 UTC
