### ISSUE TITLE
SSL regression

### ISSUE THREAD

**Issue by flotho** [redminenb/redminenb#29] opened 2015-02-20 12:09 UTC
Hy,

I recentltly updated my netbeans module and I'm no more able to connect to my servers.
The message is  :
```
Invalid response from Redmine:
com.taskadapter.redmineapi.RedmineTransportException: Cannot fetch data from https://domain.tld/projects.json : javax.net.ssl.SSLException: hostname in certificate didn't match: !=
```
I've read acrefully #26 and added the module to validate certificate, nothing appears for this specific server. Any ideas?

regards

**Comment by matthiasblaesing** [comment] 2015-02-20 16:39
Hey - did you restart after installing the "SSL Certificate Exception" module? Please do so if not.

If this fails - please provide the full message log (http://wiki.netbeans.org/FaqLogMessagesFile)

Side node: I corrected the issue title - this is _not_ a regression. The setup was broken before, it was just not reported so.

**Comment by flotho** [comment] 2015-02-22 13:33
Hy,

I've checked my ssl conf and create a SSL that match to the ServerName of my virtual host.
I restarted both Netbeans and both apache, reste the API key of my user, etc...
here are the logs :
```
SEVERE [com.kenai.redminenb.Redmine]
javax.net.ssl.SSLException: hostname in certificate didn't match: <domain.tld> != <webserver>
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:228)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:149)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:130)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:641)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:44)
Caused: com.taskadapter.redmineapi.RedmineTransportException: Cannot fetch data from https://domain.tld/issues/1570.json 
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:55)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineAuthenticator.sendRequest(RedmineAuthenticator.java:52)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.BasicSimplifier.sendRequest(BasicSimplifier.java:24)
	at com.taskadapter.redmineapi.internal.Transport.send(Transport.java:555)
	at com.taskadapter.redmineapi.internal.Transport.getObject(Transport.java:328)
	at com.taskadapter.redmineapi.internal.Transport.getObject(Transport.java:391)
	at com.taskadapter.redmineapi.IssueManager.getIssueById(IssueManager.java:85)
[catch] at com.kenai.redminenb.repository.RedmineRepository.getIssue(RedmineRepository.java:344)
	at com.kenai.redminenb.repository.RedmineRepository.getIssues(RedmineRepository.java:359)
	at com.kenai.redminenb.repository.RedmineRepositoryProvider.getIssues(RedmineRepositoryProvider.java:78)
	at com.kenai.redminenb.repository.RedmineRepositoryProvider.getIssues(RedmineRepositoryProvider.java:34)
	at org.netbeans.modules.bugtracking.RepositoryImpl.getIssueImpls(RepositoryImpl.java:240)
	at org.netbeans.modules.bugtracking.tasks.TaskSchedulingManager.initializeTasks(TaskSchedulingManager.java:365)
	at org.netbeans.modules.bugtracking.tasks.TaskSchedulingManager.initializeTasks(TaskSchedulingManager.java:356)
	at org.netbeans.modules.bugtracking.tasks.TaskSchedulingManager.initializeTasks(TaskSchedulingManager.java:331)
	at org.netbeans.modules.bugtracking.tasks.TaskSchedulingManager.getScheduledTasks(TaskSchedulingManager.java:196)
	at org.netbeans.modules.bugtracking.tasks.ScheduleCategory.getTasks(ScheduleCategory.java:83)
	at org.netbeans.modules.bugtracking.tasks.dashboard.CategoryNode.getTasks(CategoryNode.java:98)
	at org.netbeans.modules.bugtracking.tasks.dashboard.TaskContainerNode.load(TaskContainerNode.java:124)
	at org.netbeans.modules.bugtracking.tasks.dashboard.TaskContainerNode.load(TaskContainerNode.java:76)
	at org.netbeans.modules.team.commons.treelist.AsynchronousNode$Loader$1.run(AsynchronousNode.java:317)
	at java.lang.Thread.run(Thread.java:745)
```
I dont know where to dig in. Additionnaly I don't find the entry for the SSL module in netbeans, how can I reset everything?

Thansk for your support

**Comment by flotho** [comment] 2015-02-22 13:35
BTW,

I'm working on Redmine 2.3.1.stable

**Comment by flotho** [comment] 2015-02-22 14:12
Maybe the problem could come from the fact that there are multiple virtual host on the same server : http://stackoverflow.com/a/27932156

**Comment by flotho** [comment] 2015-02-22 14:30
I also made another test, uninstall the ssl module, delete the module folder, try to reconnect to the redmine.
The SSL checker appears and propose me to accpet the certif forever what I've done. Unfortunately, no more success on the redmine connection.

**Comment by matthiasblaesing** [comment] 2015-02-22 14:31
Thank you for your detailed infos. I dug through the apache http client code and found the problem. 

In your case the SSL certificate is rejected because the host in the certificate does not match the hostname you connect to. This matches your virtual host scheme.

Now the "SSL Certificate Exception" does not help in this case, because the developers of apache http client decided not to use the default hostname verified from the JRE. I'll have to investigate how I can fix this.

**Comment by flotho** [comment] 2015-02-22 15:14
Hy,

Your wrote :
> In your case the SSL certificate is rejected because the host in the certificate does not match the hostname you connect to. This matches your virtual host scheme.
I don't understand well. My CN in the SSL certificate is exactly the same as the ServerName option in my virtualHost. Of course I also have others SSL certifs and hostname on the machine.
Is there any conf I can try on my apache for you?

**Comment by matthiasblaesing** [comment] 2015-02-22 15:45
Ok - first important thing: It is good, that you reported this! This problem surely affects other users too!

I did a quick'n'dirty patched version. Please grab this file:

https://github.com/redminenb/redminenb/wiki/redminenb-1.7-SNAPSHOT.jar

locate _com-kenai-redminenb-redminenb.jar_ inside your netbeans installation. Make sure netbeans is not running. Please replace that file with the file mentioned above. Now start netbeans and try to connect. Now you should be presented with a dialog telling you, that the hostname did not match and whether you want to ignore that once/forever.

**Comment by flotho** [comment] 2015-02-22 17:56
@matthiasblaesing a great thanks for your support.
I tried your patch, unfortunately, even if I replaced all the com-kenai-redminenb-redminenb.jar by your jar that I renmed, the module is not recognized. Maybe a signature issue?

**Comment by matthiasblaesing** [comment] 2015-02-22 19:10
Hm - I decided to create a "real" Testversion as 1.6.1-SNAPSHOT - you can find it here:

https://github.com/redminenb/redminenb/wiki/redminenb-1.6.1-SNAPSHOT.nbm

please install that update. To check the version(s) please check:

1. Go to Tools -> Plugins -> Installed
2. Check "Show details"
3. Now RedmineNB should show up as 1.6.1
4. SSL Certificate Exception should show up as 0.9
5. Both modules need to be marked active

After that try to connect to your redmine installation - this should now bring the dialog I described above.

**Comment by flotho** [comment] 2015-02-22 20:04
A great thanks to you, it works perfectly!

**Comment by flotho** [comment] 2015-02-22 22:35
I'll let you close the issue

**Comment by matthiasblaesing** [comment] 2015-02-24 20:02
Thank you for your verification! I'll have another look at the implementation, give the case some more time and will fold this into another release. I'll close this when I finalize the fix.

**Closed** 2015-03-04 21:45 UTC
