### ISSUE TITLE
Unable to "Create Task Repository"; invalid response (exception about "Bad date value")

### ISSUE THREAD

**Issue by mlncn** [redminenb/redminenb#27] opened 2015-02-16 01:55 UTC
Redmine URL is set correctly (without https; i know we should have it but we don't yet) and the access key, and the same response given to my username or an arbitrary string for the name.

```
Invalid response from Redmine:
com.taskadapter.redmineapi.RedmineFormatException: org.json.JSONException: Bad date value 2011-06-05T23:32:48.000GMT-00:00
```

(If i put in a nonsense, definitely-not-correct Access Key, i get the response "Successfully authenticated"!)

Any idea what might be wrong?  I can see it's working for most people.

Version 2.5.2.devel of Redmine, Ruby version 2.1.5-p273 (2014-11-13) [x86_64-linux-gnu], and Rails version 4.1.8.

Version 1.6 of RedmineNB.

Thanks!

**Comment by matthiasblaesing** [comment] 2015-02-16 21:00
Please provide the full stack trace - before analysing the "real" conversation,  the message.log might contain enough information.

http://wiki.netbeans.org/FaqLogMessagesFile

Please upload it somewhere where I can access it.

**Comment by mlncn** [comment] 2015-02-17 07:05
Thanks!

http://data.agaric.com/sites/default/files/raw_files/messages.log

Come to think of it, it's rather odd that the date that's causing problems is four years old...

**Comment by matthiasblaesing** [comment] 2015-02-17 18:45
This looks like fail in the data serializer. From some google runs it looks like redmine tends to change dateformats (I mean - why stick with one if there are so many to change from ...).

Please grab:

https://github.com/redminenb/redminenb/wiki/redmine-java-api-2.0.0-mb3.jar

This is a patched version of the client library compiled with an additional dateformat. Please place that library in netbeans folder as:

<netbeans>/redminenb/modules/ext/com.kenai.redminenb.redminenb/com-taskadapter/redmine-java-api.jar

replacing the existing one. If that works, you can use that version and I will try to get that change upstream.

**Comment by mlncn** [comment] 2015-02-19 16:55
Thanks!  May take a little while to try this on our server; should be back to you by next week.

**Comment by matthiasblaesing** [comment] 2015-02-24 19:59
Benjamin, did you find some time to test? You might have seen, that some more bugs were fixed, so I'd like to know whether the change above fixed the problem and include it if it does.

**Comment by SergeyLee** [comment] 2015-02-25 14:58
Hello, I have test your decision - redmine-java-api-2.0.0-mb3.jar to /redminenb/modules/ext/com.kenai.redminenb.redminenb/com-taskadapter/redmine-java-api.jar.
But have this "Invalid response from Redmine...".
NetBeans 8.0.2.

**Comment by matthiasblaesing** [comment] 2015-02-25 17:50
Hey Sergey, please also provide your messages.log without it I can speculate, but can't act on it.

**Comment by SergeyLee** [comment] 2015-02-25 19:43
Ok!
https://dl.dropboxusercontent.com/u/15143203/messages.log
Please, tell me, if this link don't open.

**Comment by matthiasblaesing** [comment] 2015-02-25 20:21
Thank you - but the log indicates, that you are still on the old version. I went ahead and did a complete testbuild:

https://github.com/redminenb/redminenb/wiki/redminenb-1.6.1-SNAPSHOT.nbm

Please install that module, make sure netbeans is restartet and test again.

**Comment by SergeyLee** [comment] 2015-02-25 20:39
Yes! It works! Thanks!

**Comment by matthiasblaesing** [comment] 2015-02-25 21:21
Very good - to make this easier to upstream - could you please give the following info:

- redmine version
- ruby version
- operating system and version
- how was it installed (linux distribution package/download)?

These infos will be asked when I try to push this upstream.

Maybe your redmine installation is publicly available (readonly access is enought - I just like to see the problem in action.

Thank you for testing!

**Comment by SergeyLee** [comment] 2015-02-26 13:47
redmine - 3.0.0, ruby - 2.2.0, OS - MacOSX 10.10.2
I download redline 3.0.0 and install it by instructions. Update ruby to 2.2.0.

**Comment by matthiasblaesing** [comment] 2015-02-26 19:30
Thank you! This confirmed my suspicion it is the upgrade to redmine 3.0.0 - I upgraded my bitnami test installation and can now reproduce the issue.

**Comment by stu** [comment] 2015-02-28 02:53
was running redmine 2.6.1 and was getting this bad date issue with "2009-01-14T16:23:53.000Z".. installed your 1.6.1-snapshot and it resolved my issue!

**Comment by matthiasblaesing** [comment] 2015-03-04 21:13
Thank you all for testing - I pushed a nightly build branch as: https://github.com/matthiasblaesing/redmine-java-api/tree/redminenb until these changes are merged.

I'll be closing this and try to release a new version some time around the week end, that folds together the bugfixes.

**Closed by matthiasblaesing** 2015-03-04 21:13 UTC
